### ISSUE TITLE
Fatal error: Cannot redeclare class acf_location_nav_menu

### ISSUE THREAD

**Issue by rvpatel** [DenisYakimchuk/ACF-Location-Nav-Menu#10]
Fatal error: Cannot redeclare class acf_location_nav_menu in \wp-content\plugins\location-nav-menu-for-acf\acf_location_nav_menu.php on line 242

**Comment by rvpatel** [comment]
change class name with another

**Comment by DHappiness** [comment]
Why aren't you using built-in ACF functionality? This addon doesn't supported any more.

**Comment by DenisYakimchuk** [comment]
Why aren't you using built-in ACF functionality? This addon doesn't supported any more.
