### ISSUE TITLE
Fatal error with ACF 5.6.0

### ISSUE THREAD

**Issue by luukdv** [DenisYakimchuk/ACF-Location-Nav-Menu#7]
The class name `acf_location_nav_menu` is used by ACF itself: `PHP Fatal error:  Cannot declare class acf_location_nav_menu, because the name is already in use`.

**Comment by DenisYakimchuk** [comment]
Seems like developers of ACF PRO Plugin finally added similar functionality. If you're using the latest version of the plugin you already don't need the Add-on.
