### ISSUE TITLE
Fatal error: Call to undefined function acf_enqueue_scripts()

### ISSUE THREAD

**Issue by vosaan** [DenisYakimchuk/ACF-Location-Nav-Menu#8]
Добрый день. Установил плагин и при попытке зайти в раздел "Меню" в админке получаю ошибку:

Fatal error: Call to undefined function acf_enqueue_scripts() in D:\www\wpkf.local\wp-content\plugins\location-nav-menu-for-acf\acf-location-nav-menu.php on line 104

Можно ли это как-то побороть?

**Comment by DenisYakimchuk** [comment]
Здравствуйте, плагин ACF уже длительное время поддерживает "из коробки" добавление полей к меню. В данном аддоне больше нет нужды, в связи с чем его поддержка и развитие прекращены.
