### ISSUE TITLE
Publish updates to wordpress.org

### ISSUE THREAD

**Issue by timcv** [DenisYakimchuk/ACF-Location-Nav-Menu#9]
Hi,

At https://wordpress.org/plugins/location-nav-menu-for-acf/ latest version is 1.1.1. Im using composer to pull plugins via https://wpackagist.org/ which depends on wordpress.org.

Could you please update the wordpress.org repo with the latest version?

Thanks in advance!

//Tim

**Comment by DenisYakimchuk** [comment]
This addon isn't supported any more. Please use built-in ACF functionality.
